spring:
  application:
    name: story_helper_auth
  data:
    cassandra:
      keyspace-name: story_helper_auth
  liquibase:
    enabled: true
    url: jdbc:cassandra://127.0.0.1:9042/story_helper_auth?compliancemode=Liquibase&localdatacenter=datacenter1
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
  datasource:
    url: jdbc:cassandra://127.0.0.1:9042/story_helper_auth?compliancemode=Liquibase&localdatacenter=datacenter1
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    hikari:
      minimum-idle: 1

server:
  port: 8080
  servlet:
    context-path: /story_helper_auth

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
