spring:
  application:
    name: story_helper_back
  data:
    cassandra:
      keyspace-name: story_helper

  kafka:
    bootstrap-servers: localhost:9092

  topics:
    logs-topic: logs
    logs-group-id: logs_group_id
 liquibase:
   enabled: true
   url: jdbc:cassandra://127.0.0.1:9042/story_helper?compliancemode=Liquibase&localdatacenter=datacenter1
   change-log: /db/changelog.xml
   driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
   changeLogFile: /db/changelog.xml

server:
  port: 8090
  servlet:
    context-path: /story_helper_back

auth:
  check:
    url: http://localhost:8080/story_helper_auth/token/check
